python logicMain_rewrite.py "../" "1gram" "de_pca"  "./1gram+de_pca"
python logicMain_rewrite.py "../" "1gram" "de_lda"  "./1gram+de_lda"
python logicMain_rewrite.py "../" "1gram" "de_ps"  "./1gram+de_ps"
python logicMain_rewrite.py "../" "1gram" "de_rf"  "./1gram+de_rf"
python logicMain_rewrite.py "../" "1gram" "de_c2"  "./1gram+de_c2"
python logicMain_rewrite.py "../" "1gram" "de_mic"  "./1gram+de_mic"
python logicMain_rewrite.py "../" "1gram" "de_f_and_p_value"  "./1gram+de_f_and_p_value"

python logicMain_rewrite.py "../" "2gram" "de_pca"  "./2gram+de_pca"
python logicMain_rewrite.py "../" "2gram" "de_lda"  "./2gram+de_lda"
python logicMain_rewrite.py "../" "2gram" "de_ps"  "./2gram+de_ps"
python logicMain_rewrite.py "../" "2gram" "de_rf"  "./2gram+de_rf"
python logicMain_rewrite.py "../" "2gram" "de_c2"  "./2gram+de_c2"
python logicMain_rewrite.py "../" "2gram" "de_mic"  "./2gram+de_mic"
python logicMain_rewrite.py "../" "2gram" "de_f_and_p_value"  "./2gram+de_f_and_p_value"


python logicMain_rewrite.py "../" "3gram" "de_pca"  "./3gram+de_pca"
python logicMain_rewrite.py "../" "3gram" "de_lda"  "./3gram+de_lda"
python logicMain_rewrite.py "../" "3gram" "de_ps"  "./3gram+de_ps"
python logicMain_rewrite.py "../" "3gram" "de_rf"  "./3gram+de_rf"
python logicMain_rewrite.py "../" "3gram" "de_c2"  "./3gram+de_c2"
python logicMain_rewrite.py "../" "3gram" "de_mic"  "./3gram+de_mic"
python logicMain_rewrite.py "../" "3gram" "de_f_and_p_value"  "./3gram+de_f_and_p_value"


python logicMain_rewrite.py "../" "mix" "de_pca"  "./mix+de_pca"
python logicMain_rewrite.py "../" "mix" "de_lda"  "./mix+de_lda"
python logicMain_rewrite.py "../" "mix" "de_ps"  "./mix+de_ps"
python logicMain_rewrite.py "../" "mix" "de_rf"  "./mix+de_rf"
python logicMain_rewrite.py "../" "mix" "de_c2"  "./mix+de_c2"
python logicMain_rewrite.py "../" "mix" "de_mic"  "./mix+de_mic"
python logicMain_rewrite.py "../" "mix" "de_f_and_p_value"  "./mix+de_f_and_p_value"